### ISSUE TITLE
Inappropriate access check

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#11]
Controlling access to scripts like this
```
$istudent = has_capability('mod/assignment:submit', $context, null, false);
if ($istudent) {
    print_error("Students can not use this page!");
}
```
is completely wrong. You should have your capability to view that page, and require it explicitly granted. There are many roles that do not have permission to submit legacy assignments - yet it does not mean they can access this page.

**Comment by mgardener** [comment]
It is added. Thank you.
