### ISSUE TITLE
use function require_capability instead of is_siteadmin

### ISSUE THREAD

**Issue by mkpelletier** [fernandooliveira/moodle-block_mentor#12]
Hello.  Thanks for this fantastic plugin.  I have one suggestion.  The string isadmin prevents full use of this plugin by system registrars or admin users that are not site_admins.  It would make sense to use require_capability instead so this can be fine tuned without having to compromise site security.

**Comment by fernandooliveira** [comment]
Fixed with  block/ned_mentor:manageall
