### ISSUE TITLE
Block does not display for mentor

### ISSUE THREAD

**Issue by richardsonsamuel** [fernandooliveira/moodle-block_mentor#14]
Not sure if this is because I have set the role permissions of the mentor wrongly. **Assume the user that is logged in is the Mentor user** not the admin user

The block currently does not display for the Mentor when editing is turned off. When accessing the /block/ned_mentor/course_overview.php page manually (even though the block does not display) it returns this error:
```
Invalid user

More information about this error

Debug info: SELECT * FROM {user} WHERE id = ?
[array (
0 => 0,
)]
Error code: invaliduser
Stack trace:
line 1455 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1431 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 78 of /blocks/ned_mentor/course_overview.php: call to moodle_database->get_record()
````

### **MORE INFORMATION**
_Moodle Version Details:_
`version  = 2015111603.05
release  = 3.0.3+ (Build: 20160407)
branch   = 30
maturity = MATURITY_STABLE
`
_Server Details:_
`MYSQL/APACHE
`

**Comment by fernandooliveira** [comment]
Thanks Samuel. Looking into it.

**Comment by jellysmith** [comment]
I'm having the same problem. Everything installed nicely, and setting up mentors/mentees was a breeze, but when I log out as admin and log back in as mentor, there is nothing :-(

**Comment by fernandooliveira** [comment]
Could you check to see if the mentor role has the view permission enabled, as shown here: http://screencast.com/t/Dwh96nJRc

**Comment by jellysmith** [comment]
Aha!  That fixed it. My sample mentor can now see the block.
