### ISSUE TITLE
"Run now" not sending emails

### ISSUE THREAD

**Issue by jellysmith** [fernandooliveira/moodle-block_mentor#15]
I set up a few test situations that should have triggered notifications. To test them, I clicked "Run Now" and it appeared to process correctly, but then returns the message that no emails were sent.

**Comment by jellysmith** [comment]
Fernando, you just completely solved my block view problem with permissions... is there a similar solution for emails here that I've overlooked?

**Comment by fernandooliveira** [comment]
Hello, I could not reproduce this problem. Do you have a test site I can access?
