### ISSUE TITLE
open progress reports > generate new list

### ISSUE THREAD

**Issue by ruiruas** [fernandooliveira/moodle-block_mentor#17]
Hi Fernando,
I'm having a problem with "open progress reports".
I select "open progress reports" > "select student" > "all students" > "generate new list" 
Then moodle processes about 90% and stops with an sql error stating there are too many columns.
From the output, I think it creates 2 columns for each activity and since Innodb has a limit of 1000 columns per table it stops.
Is there a way to solve this problem? I currently have over a 1000 activities graded, so this way it doesn't work.
Any help would be appreciated, since your block is great and we 'd like to keep using it.
Best regards,
Rui

**Comment by fernandooliveira** [comment]
Hello Rui, How many courses are you trying to process?
