### ISSUE TITLE
No mentors/mentees view

### ISSUE THREAD

**Issue by KellerChr** [fernandooliveira/moodle-block_mentor#18]
Hey,

i have problems with the block view. I created the mentor role and the mentor user role as the manual described (without any permissions). If I was logged in as an administrator, the mentor manager block shows all mentors with mentees.. but even if I logged in with an account that has the mentor role (or mentor user role) theres no manager block. 

I've seen the "Block does not display for mentor #14" issue and set the permission afterwards and the block appears in the mentor role but shows ALL mentors with mentees (as the admin view). If I'm logged in as an account with the mentor user role, there shows no block at all.

Have I set some permissions or other configs?

Moodle 3.1+ (Build: 20160707) 
NED Mentor Manager
block_ned_mentor
2.9d
2016052400

Thank you very much

**Comment by athena79** [comment]
I have the same question
![image](https://cloud.githubusercontent.com/assets/20713177/17232145/66837024-5526-11e6-945e-fcbfae0359c3.png)

![image](https://cloud.githubusercontent.com/assets/20713177/17232201/a8a1616e-5526-11e6-9877-4b2845bca746.png)

the mentors dosen't see the mentors block

Do I set some other permissions or other configs?

**Comment by KellerChr** [comment]
Hey!

which Moodle version do you use (with build) and which NED Mentor Manager version? My Mentor Manager always called "Mentor Manager" even in the student Version as also in the mentor view.

But in your student view it's called "my Mentors". 

Do you check your Mentor-System permissions? As in issue #14 described? "Could you check to see if the mentor role has the view permission enabled, as shown here: http://screencast.com/t/Dwh96nJRc"

**Comment by athena79** [comment]
My moodle version is Moodle 3.1 (Build: 20160523)
and mentors block is 2.9d 2015123100

And I don't have the view. 
![image](https://cloud.githubusercontent.com/assets/20713177/17271189/c9b53f56-5675-11e6-9ddb-051bbe6186de.png)

**Comment by athena79** [comment]
The last version doesn't install.... There is an error in name plug in....
![image](https://cloud.githubusercontent.com/assets/20713177/17288188/fe20cf12-57d3-11e6-966d-6d83c3243b5b.png)

**Comment by KellerChr** [comment]
Yeah

"We are working on an updated version of this plug-in for Moodle 2.9, 3.0 and 3.1. Anyone who wants to test the latest (stable) code can do so by following these directions:
1.Remove and old version of this plug-in from your test site
2.Download the latest code here: http://tinyurl.com/jede3l9
3.Rename directory to ned_mentor and upload it to the /blocks folder on your Moodle server (note that the name of the plug-in directory is now ned_mentor, not fn_mentor)
4.Login to your Moodle site and complete the installation as per usual"


You have to go like this! Unzip it and rename it to ned_mentor and put in in the blocks folder! :-) 

I tried "your" Version in my moodle Installation and it seems it works better as the newest one from github.

**Comment by KellerChr** [comment]
You also could try to rename your zip file into: block_ned_mentor_moodle31_2016052400.zip and upload it as you tried before!

I downloaded the github Version on mach 20 2016 after the POET pull request. It seems that this Version running the best in my Version. It shows the "my Mentors" block correctly in the Student view and shows correctly only the mentees of the Mentor in the Mentor view! I don't know whats wrong in the "ned_mentor" Version but in the latest "fn_mentor" Version it works correctly.

**Comment by fernandooliveira** [comment]
Hello KellChr, 

Just to be clear, your main issue is that "the block appears in the mentor role but shows ALL mentors with mentees" ? If so, we have identified this problems and will apply a fix soon. Thanks.

**Comment by mkpelletier** [comment]
Hello Fernando,

Yes, that is correct.  The block shows, but when logged in as a mentor, he/she can see all students and the other mentors as well.  I am looking forward to your fix.  Thanks again!

Best Regards,

Mathieu

**Comment by KellerChr** [comment]
Hey,

one of the main issue is that "the block appears in the mentor role but shows ALL mentors with mentees" right!

The other issue is that the student doesn't see the block and thus he can't see his mentor.

Kind Regards,

Christopher
