### ISSUE TITLE
Ned_mentor manager block showing students not assigned to mentor

### ISSUE THREAD

**Issue by mkpelletier** [fernandooliveira/moodle-block_mentor#19]
Hello Fernando,

Thanks for the fantastic block.  I have an issue in the newest version.  I cloned from github directly.  Here are my particulars:

Moodle version: 3.0.4
Block version: 2016081500

I have installed as per instructions, setting only block/ned_mentor:viewblock to Allow.  All other permissions for the mentor role are not set.

The result is as follows:
Every mentor can view the students and other mentors in his/her list.  See the screenshot:
![mysats](https://cloud.githubusercontent.com/assets/4638072/17729077/a7b50fa8-6462-11e6-9a6c-49c13c16a9b4.jpg)

Any ideas on how to fix this?  fn_mentor did not seem to have this issue.

Thanks for your help!

**Comment by fernandooliveira** [comment]
Thanks. This has been fixed.
