### ISSUE TITLE
CSS selectors' scope

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#2]
Not quite sure what was meant by the reported issue #1 here so just in case it is something different, I am reporting this as an individual issue.

The current file styles.css contains quite a few CSS selectors that are likely to affect areas outside the block scope. See https://docs.moodle.org/dev/Plugin_contribution_checklist#CSS-styles for more information.

**Comment by fernandooliveira** [comment]
fixed

**Comment by mudrd8mz** [comment]
No, it is not.
