### ISSUE TITLE
Enhancement: Manage mentors -> Add Cohorts

### ISSUE THREAD

**Issue by KellerChr** [fernandooliveira/moodle-block_mentor#20]
Hello,

I have a suggestion for improvement. We have a high amount of users and also a high turnover. Our Moodle users are based on an Active Directory and will auto assign to groups based on their profile fields.

So it would be easier to manage if there are a possibility to assign cohorts to a mentor. Or "just easily" add all members of an cohort. 

Maybe show the individual cohorts in the drop down menu where "all students" is selected at the manage mentor site. 

Select the Mentor -> Select the cohort in drop down -> add all

Kind regards,

Christopher

**Comment by KellerChr** [comment]
found this plugin out, which is also based on profile fields. 

https://moodle.org/plugins/auth_enrolmentor

That would fit perfectly in combination with the ned mentor manager. Perhaps there held a cooperation? Unfortunately, this plugin does not work in version 3.1.

It is very difficult for me (and maybe another) without an automatic assignment of the mentees to mentors to use the plugin. 

Currently I'm doing every day manual allocations among mentors.

Kind regards,

Christopher

**Comment by fernandooliveira** [comment]
Thanks for your suggestion. We will consider this option if/when funding becomes available.
