### ISSUE TITLE
Wrong Characters in table field "Name" (all_students.php)

### ISSUE THREAD

**Issue by gethanos** [fernandooliveira/moodle-block_mentor#23]
Hi,
I had to change
  $tablerow->$column = (strlen($tablerow->$column) > 16) ? substr($tablerow->$column, 0, 16) : $tablerow->$column;

to something bigger like
                $tablerow->$column = (strlen($tablerow->$column) > 200) ? substr($tablerow->$column, 0, 200) : $tablerow->$column;

In order to show correctly All the Greek Characters on name otherwise the last character shows a "?" (wrong character size probably)

Kind Regards,
Thanos

**Comment by fernandooliveira** [comment]
Hello Thanos, 
This change was made to address the issue: https://github.com/fernandooliveira/moodle-block_mentor/commit/58a08a57a78bdd7cfe0682f098191ad328c90faf
