### ISSUE TITLE
Batch upload?

### ISSUE THREAD

**Issue by kimberwarden** [fernandooliveira/moodle-block_mentor#25]
This is an awesome block, and I'd LOVE to use it! Is there any way to assign/unassign mentors to students via a .csv upload? We have too many students to keep up with doing it by hand.

**Comment by KellerChr** [comment]
Hey,

I had a similar problem. You can add an additional profile field and update the data via csv. https://docs.moodle.org/31/en/Upload_users

This Plugin: https://github.com/eSrem/moodle-auth_enrolmentor uses the self created profile field to assign mentors to anyone who has the ID, E-Mail or Username in this profile field.

Maybe it's helpful for you

**Comment by fernandooliveira** [comment]
We currently do not have this functionally but we hope to develop it in the next few months, if we can get enough funds together. Feel free to contribute :)

**Comment by fernandooliveira** [comment]
I have added this item to the wish list: http://ned.ca/plugins/#group
