### ISSUE TITLE
You are not allowed to assign this role

### ISSUE THREAD

**Issue by horstschneider** [fernandooliveira/moodle-block_mentor#26]
Dear all,

Today I upgraded to the latest version of the mentor manager on moodle.
After uninstalling the old plugin I deleted the folder ned_mentor and uploaded the folder fn_mentor.

I also deleted the previous roles (mentor-system and mentor-user) from the system. Afterwards I created both roles again by importing the xml-files that are available as a download following the installation instructions on http://ned.ca/mentor-manager/.

When I tried to assign the mentor role to a user I received the following message:
"You are not allowed to assign this role (id = 11) in this context (System)"

I can assign the Mentor-system role in Site administration/Users/Permissions/Assign system roles to users. But they do not show up as mentors when I click on Manage mentors in the Mentor Manager block.

Any help appreciated as we really love the plugin.

Moodle version 2016052301 Moodle release 3.1.1 (Build: 20160711)
Plugin version 3.1.2 (2016091500)
Database type mysql (5.5.52-0+deb8u1)

Kind regards

Horst

**Comment by fernandooliveira** [comment]
Can you indicate your version number of PHP ? thanks

**Comment by horstschneider** [comment]
PHP Version 5.6.24-0+deb8u1




________________________________
Von: NED <notifications@github.com>
Gesendet: Dienstag, 27. September 2016 05:18
An: fernandooliveira/moodle-block_mentor
Cc: horstschneider; Author
Betreff: Re: [fernandooliveira/moodle-block_mentor] You are not allowed to assign this role (#26)


Can you indicate your version number of PHP ? thanks

-

**Comment by fernandooliveira** [comment]
Hello, can you verify that the mentor-user and mentor-system roles are set properly in Mentor Manager config page: http://screencast.com/t/mex8SI2Qo1

**Comment by horstschneider** [comment]
Yes, I confirm

Von meinem iPad gesendet



Am 01.11.2016 um 21:39 schrieb NED <notifications@github.com<mailto:notifications@github.com>>:


Hello, can you verify that the mentor-user and mentor-system roles are set properly in Mentor Manager config page: http://screencast.com/t/mex8SI2Qo1

-

**Comment by fernandooliveira** [comment]
I can't replicate this problem, but I'd be happy to take a look at your site if you can send me login details.

Thanks.

**Comment by horstschneider** [comment]
Dear all,

I uninstalled the mentor manager completely and installed the latest version.

This works now.

Thanks for trying to help.

Kind regards

Horst


Horst Schneider
Opperzauer Str. 6
51570 Windeck
Tel.: 02292 9299250
Fax: 02292 9299257
Mobil: 0151-52648963


________________________________
Von: NED <notifications@github.com>
Gesendet: Mittwoch, 2. November 2016 14:47
An: fernandooliveira/moodle-block_mentor
Cc: horstschneider; Author
Betreff: Re: [fernandooliveira/moodle-block_mentor] You are not allowed to assign this role (#26)


I can't replicate this problem, but I'd be happy to take a look at your site if you can send me login details.

Thanks.

-
