### ISSUE TITLE
Queries not scaling?

### ISSUE THREAD

**Issue by evandonovan** [fernandooliveira/moodle-block_mentor#28]
(Cross-post from the plugin page on Moodle.org in case this is a more appropriate bug report venue.)

This plugin was working great for us at first, but then we started to add more mentors/mentees. Now the Mentor Manager block's "Show all mentors & mentees" & "Manage mentors" pages take over 10 minutes or so to load, if they load at all - for the users that are privileged enough to see the full list. 

I am using Moodle 3.1.1+ and the 3.1.7 version of this plugin.

I am on a CentOS 7 server running Apache 2.4.6, MariaDB 5.5.50 (a drop-in replacement for MySQL), and PHP 5.4.16. The server has ~12GB of memory, around half of which is currently free.

It seems to me that there must be something about the way that the queries are written that makes them not scale.

**Comment by fernandooliveira** [comment]
We are aware of a problem with PHP 5.4, but unfortunately, we do not have a server with that PHP version that we could test. Please consider upgrading to PHP 5.5 or 5.6. Alternatively, I'd be happy to take a closer look if you could provide Moodle login and access to database.

**Comment by evandonovan** [comment]
When you say access to the database, do you mean via SSH? What would be the best way that I could get you that access, if I were to do so?

**Comment by evandonovan** [comment]
We've decided that we are going to upgrade to at least PHP 5.5. If I still have issues, I will reopen this, but until then, I'm closing this ticket.
