### ISSUE TITLE
Mentor-system permission to see link to assignment activity

### ISSUE THREAD

**Issue by KellerChr** [fernandooliveira/moodle-block_mentor#29]
Hello,

is there an option for the mentor to see the assignment activity of his mentees?

If I was logged in as a Manager, I can click on the course grade site on a link that Redirect to the assignment activity. Which permission have to set to the mentor to make this possible?

Kind regards,

Christopher

**Comment by KellerChr** [comment]
I found out that the link to the activity will be "enabled" if the Mentor is also assigned to the course.

**Comment by fernandooliveira** [comment]
Hi Christopher,

One of the main purposes of this plug-in is to provide mentors with student-specific information related course progress without actually giving them access to the course. Once a mentor has access to a course, she/he can see information about all students, which is problematic. I've never tried, but if this is what you need, you may be able to achieve it by creating a custom role. 

Thanks,
Fernando
