### ISSUE TITLE
Undocumented post-installation steps

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#3]
I am not quite happy about all the automatic setup done in the `db/install.php`. I do understand your reasoning for making things easier for admins. But I am pretty sure that admins should be well informed about the significant changes your block does to their site's setup.

* Is allowing `moodle/user:viewdetails` for all logged-in users really necessary?
* If the site already has the role `mentor` or `mentor_user`, you are silently changing that role's permissions.

I don't think this is nice to do. If there is no other way, then all these steps must be well documented in the plugin description at the Plugins directory page and the README file. But let me suggest to move all this setup from `db/install.php` to a separate admin-only page provided by the block. This new page could provide a report of the current setup and eventually offer to perform required changes for the admin. But again, all these steps (i.e. assigning capabilities to new or existing roles) must be very well communicated with the admin imho. I don't think it is something plugins should silently do in the background. Thanks for understanding.

**Comment by fernandooliveira** [comment]
Thx. I will add a note in the Plugin page and README file.

**Comment by mudrd8mz** [comment]
Looking at this again. I still can't see an evident warning in neither the plugin page, nor the readme file. Some kind of formatting (e.g. lists or paragraphs) would help readability of both places by the way.

More and more I think about this, the more I believe that plugins should not silently change the roles setup during the installation like this. The risk for sites that already have a role "mentor" defined, is just too high. And the chance that admin of such a site will want to to try and check your plugin, is just too high.

Please, get rid of the db/install.php. Turn it into a separate "Setup wizard" or "Setup helper" script available for site administrators that would guide them through creating the required roles and setting them up. Thanks.

**Comment by fernandooliveira** [comment]
Automatic role creation feature was removed.
