### ISSUE TITLE
role configuration creates security problem

### ISSUE THREAD

**Issue by mkpelletier** [fernandooliveira/moodle-block_mentor#31]
When configured as specified by the installation documentation, using either manual or predefined xml role definition, the mentor has view access to ALL students in a course.  As far as I can tell this only applies to mod/assign.  It is expected that the mentor should only be able to view the students assigned to him/her.

Steps to recreate:
1. install the block as per the installation manual
2. assign a user to the mentor role via the block
3. assign a student to the mentor
4. login as the mentor > view student overview report
5. click an assignment (mod/assign)
6. click "view/grade all submissions" at the bottom of the summary
7. All students in the course are shown

Versions:
Moodle 3.0.4+ (Build: 20160623)
NED Mentor Manager 3.1.7 2016110100

**Comment by fernandooliveira** [comment]
I can't seem to replicate this problem. Can you please check if the latest update resolved this issue on your end?
