### ISSUE TITLE
Too many columns error when calling block_fn_mentor_generate_report

### ISSUE THREAD

**Issue by SamMcCullough** [fernandooliveira/moodle-block_mentor#32]
Hello @fernandooliveira,

While troubleshooting an error with a clients site, I found that update_all_students_data.php would generate a Too many columns error. MySQL's hard limit is 4096 columns. 

This occurred when block_fn_mentor_generate_report attempts to execute on $sqlcreate. The $fieldscreate variable generates 5644 columns. 

Myself and my colleague believe the underlying issue is the creation does not validate which courses to include. It just includes all of them. By doing so, Moodle instances with large amounts of courses and users can breach the column limit.

[too_many_tables.txt](https://github.com/fernandooliveira/moodle-block_mentor/files/600880/too_many_tables.txt)

Best Regards,
Sam McCullough
Suppor Services Manager
Lambda Solutions

**Comment by fernandooliveira** [comment]
Thanks Sam, We'll look into it.

**Comment by SamMcCullough** [comment]
Hi @fernandooliveira no problem thank you! We really like your plugin here at Lambda. A lot of our clients want to use it.

**Comment by fernandooliveira** [comment]
Hi Sam, the plugin only processes the courses that are selected in the block config page. The coder who works on this plugin can't investigate problem with the file that you provided. He needs full access, including access to database, Moodle admin and FTP. Are you able to replicate this problem on a test site? Thanks.

**Comment by SamMcCullough** [comment]
@fernandooliveira Could I provide an anonymized copy of the site to you for debugging? This would allow your developer to run it locally?

**Comment by fernandooliveira** [comment]
That should work.

**Comment by fernandooliveira** [comment]
Hi Sam, Any luck with this?
