### ISSUE TITLE
Allow mentee to see block ./. teacher role

### ISSUE THREAD

**Issue by KellerChr** [fernandooliveira/moodle-block_mentor#34]
Hey,

I set the option to allow mentees to see the mentor block to true. If a mentee has a teacher (Trainer) role in a course, the mentee see all mentees with mentors (in the whole system, not course based) in his block. The mentee are not able to see the Progress of the other mentees that are shown (error message invalid permission), but if a listed mentee is assigned in the course where the teacher (Trainer) is, the teacher be able to see the progress of his own course and others courses.

Kind regards,

Chris

**Comment by fernandooliveira** [comment]
Not sure what you mean. Perhaps you can use some screenshots?
