### ISSUE TITLE
Mentor Progress

### ISSUE THREAD

**Issue by KellerChr** [fernandooliveira/moodle-block_mentor#36]
Hey,

i found out that the mentor manager block changes the name if you are a mentee. The "My Progress" block will only appears to mentees. But if I grant them to a mentor cause he is a mentor and mentee at the same time, the selected student can't access to the own progress.

Kind regards,

**Comment by fernandooliveira** [comment]
Sorry, but this plugin wasn't designed with this functionality in mind.  A single user can have Mentor OR Mentee role but not both.
