### ISSUE TITLE
Coding Error in lib.php line 2577?

### ISSUE THREAD

**Issue by mkpelletier** [fernandooliveira/moodle-block_mentor#37]
I am getting this error when running the cronjob:

Missing argument 3 for block_fn_mentor_activity_progress(), called in blocks/fn_mentor/lib.php on line 2577 and defined in blocks/fn_mentor/lib.php on line 2134

Is $modgradesarray supposed to be specified here?

**Comment by fernandooliveira** [comment]
Thanks. This is fixed.
