### ISSUE TITLE
Suspicious references to Spark LMS

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#4]
The file https://github.com/fernandooliveira/moodle-block_mentor/blob/master/db/install.php#L3 holds references to Spark LMS.

It could be seen as the GNU/GPL violation. Please refer to https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing and https://docs.moodle.org/dev/Coding_style#Files

**Comment by fernandooliveira** [comment]
fixed
