### ISSUE TITLE
Course titles are not processed by language filters

### ISSUE THREAD

**Issue by mkpelletier** [fernandooliveira/moodle-block_mentor#43]
For multilingual sites it is important that the course titles in block mentor accommodate language string filters.  This requires the use of format_string() function to be incorporated into course_overview.php and course_overview_single.php.  I have already submitted a patch for this.

**Comment by fernandooliveira** [comment]
Thanks very much, Mathieu.  This should be resolved shortly.

**Comment by fernandooliveira** [comment]
This issue is fixed
