### ISSUE TITLE
Block data protection

### ISSUE THREAD

**Issue by KellerChr** [fernandooliveira/moodle-block_mentor#45]
Hey everyone,

if a user is assigned to a mentee as his mentor and the user is also a trainer in a course, he will be able to see all mentors/mentees in the Mentor Manager block. 

If i set the Mentor System role to the user, the user will only shown the own mentees. 

The Problem is: If i forget to set the Mentor System role there are no data protection. Is there a Chance that the user see nothing in this block when he has no Mentor System role?

**Comment by fernandooliveira** [comment]
I'm not sure if I understand the problem here, but it sounds like you are giving teachers a mentor role. If so, the block will not work properly.
