### ISSUE TITLE
Limit Courses Viewed by Current Semester Courses Only

### ISSUE THREAD

**Issue by eharris1** [fernandooliveira/moodle-block_mentor#46]
is there a way to only view current semester courses rather than every course a student has taken.  I think by limiting the courses viewed the dashboard would load quicker and would be more beneficial to faculty who are advising students based on their current semester enrollments?

**Comment by fernandooliveira** [comment]
The block config page allows you to chose the categories that you want the block to process. Hope this helps.

**Comment by eharris1** [comment]
Yes this helped!  Thank you so much.
