### ISSUE TITLE
Error when clicking "Manage Mentor Roles" button

### ISSUE THREAD

**Issue by schalkvn** [fernandooliveira/moodle-block_mentor#47]
Running Moodle 3.2, I recently installed Ned Mentor Manager. When clicking "Manage Mentor Roles" button, the following error message appears "Can not find data record in database table context."

Please advise.

![screen shot 2017-07-09 at 12 20 59 pm](https://user-images.githubusercontent.com/30025756/27996136-26cebc6e-64a1-11e7-9d7c-2cd2daa5e7a3.png)
![screen shot 2017-07-09 at 12 22 09 pm](https://user-images.githubusercontent.com/30025756/27996140-496fb17e-64a1-11e7-8064-f1b50f0082fd.png)
![screen shot 2017-07-09 at 12 22 44 pm](https://user-images.githubusercontent.com/30025756/27996145-5ee3513c-64a1-11e7-88db-8760cd8b3ccd.png)

**Comment by fernandooliveira** [comment]
Hi. Did you set up the mentor role according to the instruction in http://ned.ca/mentor-manager/ 

Can you specify plugin version and PHP version?

**Comment by schalkvn** [comment]
Fernando,

I did setup Mentor Manager as per your installation guide & double-checked

Version installed: 3.1.10 (2017051000)

PHP version: not sure (hosted by 3rd party)
Will have to get back to you.

Regards,

Schalk van Niekerk
(585) 770-0198

**Comment by schalkvn** [comment]
Running PHP Version 7.0.19

**Comment by schalkvn** [comment]
I did notice that we are running Moodle 3.2.2+ (Build: 20170324) now.

Problem still exists.

Thanks,
Schalk van Niekerk


---------- Forwarded message ----------

**Comment by fernandooliveira** [comment]
Hi Schalk, 

Are you able to provide me with access to your site so that I can see the problem first hand?
