### ISSUE TITLE
Functions in lib.php without valid component prefix

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#5]
See https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions for the reference. Functions like `get_all_students()` violate the naming rules.

**Comment by mudrd8mz** [comment]
I just realized this applies to the table name `mentors_mentees_notification` too.

**Comment by fernandooliveira** [comment]
fixed
