### ISSUE TITLE
Hard-coded role ids

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#6]
At multiple places, your code fetches the list of students by assuming that they all have assigned a role with id = 5. That is wrong for two reasons.

* The role can have different id at different sites.
* Moodle code should never check for the role. The right question is to ask for enrolled users with certain capability assigned.

The second point applies to the overall logic of your block, too. I believe it should be implemented by two capabilities provided by your block: "be mentor" and "be mentee". The capability "be mentee" should be then used to get the list of users.

**Comment by fernandooliveira** [comment]
fixed

**Comment by mudrd8mz** [comment]
It would help to actually read _what_ and _how_ was fixed.

**Comment by fernandooliveira** [comment]
Student role is set in block config page:  http://screencast.com/t/GyHCh51wpt
