### ISSUE TITLE
Why are you preventing users to put the block into their Dashboard?

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#7]
The functionality provided by the plugin is actually quite nice to fit into Dashboard - given that it provides overview across all course, too.

**Comment by fernandooliveira** [comment]
fixed

**Comment by mudrd8mz** [comment]
Is it fixed? If so, how? I can't find any referential commits and I still can't see how a teacher or a student could add the block into their Dashboard page after clicking the "Customize this page" button.

**Comment by fernandooliveira** [comment]
http://screencast.com/t/cc9kmBtooZ
