### ISSUE TITLE
Multiple coding style issues

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#8]
Just reading the code reveals quite a lot of violations against good coding guidelines outlined at https://docs.moodle.org/dev/Coding_style, https://docs.moodle.org/dev/Data_manipulation_API and others

For example `"SELECT * FROM {$CFG->prefix}assign LIMIT 0, 1"` is more than discouraged (we have different prefix syntax and there is better cross-db compatible way to specify limits).

Why does listactivities.php declares global variables if it itself runs in the global context?

etc.

**Comment by fernandooliveira** [comment]
fixed

**Comment by mudrd8mz** [comment]
You did not comment on why `global $CFG, $DB, $OUTPUT, $PAGE, $COURSE;` is there in listactivities.php. Additionally, I just spotted forgotten `$USINGHTMLEDITOR` there.

**Comment by fernandooliveira** [comment]
Unnecessary code pieces removed.
