### ISSUE TITLE
block_fn_mentor | pagelayout should really be a selection menu

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-block_mentor#9]
I don't think that administrators are aware of page layouts and possible values for that field. It is quite easy to mess up with invalid value (unknown page layout).

The form should ideally (1) provide a list of page layouts provided by the current theme and (2) fall back to a safe value if such page layout does not exist.

It seems to me that something like the following in your settings.php could do the trick (just quick guessing, there might be a better way):
```
$themeconfig = theme_config::load($CFG->theme);
$layouts = array();
foreach (array_keys($themeconfig->layouts) as $layout) {
    $layouts[$layout] = $layout;
}
```
The $layouts can be then used for `admin_setting_configselect` settings field.

But honestly, maybe leaving this hard-coded would be even better :-)

**Comment by mgardener** [comment]
Thank you for suggestion. It is corrected.

**Comment by mgardener** [comment]
Our main purpose is to hide side blocks. This is why we did it optional.
